name: Java CI/CD with GHCR

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Checkstyle for all microservices
        run: |
            for pom in $(find . -name "pom.xml" -not -path "./pom.xml"); do
              service_dir=$(dirname "$pom")
              echo "--------------------------------------------------"
              echo "Checking style in service: $service_dir"
              echo "--------------------------------------------------"
              mvn -f "$pom" checkstyle:check
            done

      - name: Run Tests for all microservices
        run: |
            for pom in $(find . -name "pom.xml" -not -path "./pom.xml"); do
              service_dir=$(dirname "$pom")
              echo "--------------------------------------------------"
              echo "Running tests in service: $service_dir"
              echo "--------------------------------------------------"
              mvn -f "$pom" clean test
            done

  publish-to-ghcr:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set short git commit SHA
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Auth-Service
        uses: docker/build-push-action@v5
        with:
          context: ./auth-service
          file: ./auth-service/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/auth-service:latest
            ghcr.io/${{ github.repository_owner }}/auth-service:${{ steps.vars.outputs.sha_short }}

      - name: Build and Push Api-Gateway
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          file: ./api-gateway/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/api-gateway:latest
            ghcr.io/${{ github.repository_owner }}/api-gateway:${{ steps.vars.outputs.sha_short }}

      - name: Build and Push Inventory-Service
        uses: docker/build-push-action@v5
        with:
          context: ./inventory-service
          file: ./inventory-service/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/inventory-service:latest
            ghcr.io/${{ github.repository_owner }}/inventory-service:${{ steps.vars.outputs.sha_short }}

      - name: Build and Push Notification-Service
        uses: docker/build-push-action@v5
        with:
          context: ./notification-service
          file: ./notification-service/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/notification-service:latest
            ghcr.io/${{ github.repository_owner }}/notification-service:${{ steps.vars.outputs.sha_short }}

      - name: Build and Push Order-Service
        uses: docker/build-push-action@v5
        with:
          context: ./order-service
          file: ./order-service/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/order-service:latest
            ghcr.io/${{ github.repository_owner }}/order-service:${{ steps.vars.outputs.sha_short }}

      - name: Build and Push Product-Service
        uses: docker/build-push-action@v5
        with:
          context: ./product-service
          file: ./product-service/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/product-service:latest
            ghcr.io/${{ github.repository_owner }}/product-service:${{ steps.vars.outputs.sha_short }}

      - name: Build and Push User-Service
        uses: docker/build-push-action@v5
        with:
          context: ./user-service
          file: ./user-service/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/user-service:latest
            ghcr.io/${{ github.repository_owner }}/user-service:${{ steps.vars.outputs.sha_short }}